Import library

In [1]:
import pandas as pd

In [2]:
sales=pd.read_csv("./datasets/sales.csv")
sales.head()

         date  item_id  price  item_count
0  2019-01-01        3  29.22         2.0
1  2019-01-01        4  26.42        22.0
2  2019-01-01       12   4.87         7.0
3  2019-01-01       13   4.18        12.0
4  2019-01-01       16   3.21       136.0

In [3]:
items=pd.read_csv("./datasets/items.csv")
items.head()

   id  store_id                               name  kcal   cost
0   1         4                     Chocolate Cake   554   6.71
1   2         4  Breaded Fish with Vegetables Meal   772  15.09
2   3         1                  Sweet Fruity Cake   931  29.22
3   4         1    Amazing Steak Dinner with Rolls   763  26.42
4   5         5                          Milk Cake   583   6.07

In [5]:
df=sales.copy()
df['name']=df['item_id'].map(items.set_index('id')['name'].str.lower().str.replace(" ", "_"))
df['kcal']=df['item_id'].map(items.set_index("id")["kcal"])

df.head()

,date,item_id,price,item_count,name,kcal
0,2019-01-01,3,29.22,2.0,sweet_fruity_cake,931
1,2019-01-01,4,26.42,22.0,amazing_steak_dinner_with_rolls,763
2,2019-01-01,12,4.87,7.0,fantastic_sweet_cola,478
3,2019-01-01,13,4.18,12.0,sweet_frozen_soft_drink,490
4,2019-01-01,16,3.21,136.0,frozen_milky_smoothy,284

In [8]:
df['date']=pd.to_datetime(df['date'])

In [9]:
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['day'] = df['date'].dt.day

df.head()

,date,item_id,price,item_count,name,kcal,month,year,day
0,2019-01-01,3,29.22,2.0,sweet_fruity_cake,931,1,2019,1
1,2019-01-01,4,26.42,22.0,amazing_steak_dinner_with_rolls,763,1,2019,1
2,2019-01-01,12,4.87,7.0,fantastic_sweet_cola,478,1,2019,1
3,2019-01-01,13,4.18,12.0,sweet_frozen_soft_drink,490,1,2019,1
4,2019-01-01,16,3.21,136.0,frozen_milky_smoothy,284,1,2019,1

In [10]:
df.dropna()

,date,item_id,price,item_count,name,kcal,month,year,day
0,2019-01-01,3,29.22,2.0,sweet_fruity_cake,931,1,2019,1
1,2019-01-01,4,26.42,22.0,amazing_steak_dinner_with_rolls,763,1,2019,1
2,2019-01-01,12,4.87,7.0,fantastic_sweet_cola,478,1,2019,1
3,2019-01-01,13,4.18,12.0,sweet_frozen_soft_drink,490,1,2019,1
4,2019-01-01,16,3.21,136.0,frozen_milky_smoothy,284,1,2019,1
...,...,...,...,...,...,...,...,...,...
109595,2021-12-31,96,21.93,0.0,blue_ribbon_fish_with_bread_lunch,708,12,2021,31
109596,2021-12-31,97,28.65,0.0,original_fruity_cod_with_bread_and_vegetables_...,744,12,2021,31
109597,2021-12-31,98,5.00,0.0,original_sweet_milky_soft_drink,579,12,2021,31
109598,2021-12-31,99,5.32,0.0,frozen_tomato_soft_drink,423,12,2021,31
109599,2021-12-31,100,2.48,0.0,awesome_vodka_cocktail,223,12,2021,31

In [11]:
df.to_csv("./datasets/cleaned_data.csv")